version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                      
    schedule:
      interval: "daily"                 
      time: "04:00"                     
      timezone: "America/Fortaleza"     
    open-pull-requests-limit: 7         
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "thiag0bezerra"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/Fortaleza"
    open-pull-requests-limit: 5
    labels:
      - "actions"
    reviewers:
      - "thiag0bezerra"
